language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feeditem -f Microservice/udagram-api-feeditem/Dockerfile Microservice/udagram-api-feeditem
  - docker build -t udagram-api-user -f Microservice/udagram-api-user/Dockerfile Microservice/udagram-api-user
  - docker build -t udagram-frontend -f Microservice/udagram-frontend/Dockerfile Microservice/udagram-frontend
  - docker tag udagram-api-feeditem blodemaster/udagram-api-feeditem:latest
  - docker tag udagram-api-user blodemaster/udagram-api-user:latest
  - docker tag udagram-frontend blodemaster/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push blodemaster/udagram-api-feeditem:latest
  - docker push blodemaster/udagram-api-user:latest
  - docker push blodemaster/udagram-frontend:latest

